version: "3.7"
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: remote-tailscale
    hostname: remote-tailscale
    # ports:
    #   - 172.17.0.1:53:53/udp
    environment:
      - TS_AUTHKEY=tskey-auth-kZGYHc6CNTRL-tnZ6BVo7RvA6p7AmmmUsvAYohNL4MECPE
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ROUTES=172.18.0.0/24
      - TS_EXTRA_ARGS=--ssh --accept-routes
    volumes:
      - ${TAILSCALE_CONFIG_DATA}/state:/var/lib/tailscale
      # - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  dnsdock:
    container_name: remote-dnsdock 
    command: ["--alias"] # makes each service use it's 
    image: aacebedo/dnsdock:latest-amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: service:tailscale
    depends_on:
      - tailscale
    labels:
      - com.dnsdock.ignore=true
