version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: mgmt-homepage
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${HOMEPAGE_CONFIG_DATA}:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    # labels:
    #   - com.dnsdock.alias=homepage